# Site settings
name: sky知识库
email: ht_gaolitian@126.com
author: litiansky
url: https://litiansky.github.io/skyblog/ 
resume_site: https://litiansky.github.io/skyblog/ 
github: https://github.com/litiansky/
baseurl: ""
description: 加油！坚持！坚毅！
meta_description: sky;个人博客;高立天;知识库;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 个人知识库整理记录
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: litiansky
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : litiansky
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
